### ISSUE TITLE
Comments system for the blog posts

### ISSUE THREAD

**Issue by asmeurer** [oscarbenjamin/blog#1]
If it isn't too hard, it would be useful to add a comments section to the bottom of the post so people can discuss things. Maybe you can try Utterances https://www.asmeurer.com/blog/posts/switching-to-utterances-comments/ (see https://sphinx-comments.readthedocs.io/en/latest/utterances.html).

**Comment by oscarbenjamin** [comment]
I think I have this working with utterances now.

**Comment by oscarbenjamin** [comment]
Thanks for the tip
